version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./initdb/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  postgres:
    image: postgres:9.6
    volumes:
      - ./initdb/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
